spring:
  profiles:
    active: local
  application:
    name: FlightNetWork
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: root
server:
  port: 8585
logging:
  level:
    com.flightNetWork: TRACE
---
# Env specific profile
spring:
  profiles:
    active: junit
  application:
    name: FlightNetWork
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: root
logging:
  level:
    com.flightNetWork: TRACE